#!/usr/bin/env groovy

node {
      
     stage ('SCM checkout'){
     git 'https://github.com/surya-pandey/AppiumTesting.git'
     }

    stage('check java') {
        sh "java -version"
    }

    stage('clean') {
        sh "chmod +x mvnw"
        sh "./mvnw clean"
    }
    
    stage('validate') {
        sh "chmod +x mvnw"
        sh "./mvnw validate"
    }
    stage('build') {
        sh "chmod +x mvnw"
        sh "./mvnw build"
    }

        stage ('Test Stage') {
            steps {
                withMaven(maven : 'maven_6_3_3') {
                    sh 'mvn test'
                }
            }
        }
        stage ('package Stage') {
            steps {
                withMaven(maven : 'maven_3_6_3') {
                    sh 'mvn package'
                }
            }
        }
         stage ('install Stage') {
            steps {
                withMaven(maven : 'maven_6_3_3') {
                    sh 'mvn install'
                }
            }
        }
    }
}