pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn clean'
                }
            }
        }

        stage ('Validation  Stage') {

            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn validate'
                }
            }
        }


        stage ('Build Stage') {
            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn build'
                }
            }
        }
        stage ('Test Stage') {
            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn test'
                }
            }
        }
        stage ('package Stage') {
            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn package'
                }
            }
        }
         stage ('install Stage') {
            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn install'
                }
            }
        }
    }
}