node {
    stage ('clean'){
         sh label: 'clean', script: 'mvn clean'
    }
      stage('validate') {
        sh "chmod +x mvnw"
        sh label: 'validate', script: 'mvn validate'
    }
    stage('build') {
        sh "chmod +x mvnw"
        sh label: 'build', script: 'mvn build'
    }
    stage('test Stage')
       steps{
           withMaven(maven : 'maven_6_3_3') {
                              sh "mvn test"
                          }
    }
    stage('install stage'){
           steps {
                withMaven(maven : 'maven_6_3_3') {
                    sh 'mvn install'
                }
            }
     
    }
   


        
}
